# Generated by Django 5.0.7 on 2024-11-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_cameraconfiguration_success_sound_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='computer_number',
            field=models.CharField(default='00000000000', max_length=255),
        ),
    ]
